Repository 2024-2025-AGH-Wstep-do-Informatyki/Othello, pull requests merged in 2024-12, with the labels that each got.

#10 Pawel branch
  Gałąź-Paweł/Plansza
Labels: documentation

#12 add save/read game file
  szymon-branch/save_game_to_file.py
Labels: Opcjonalne

#11 CREATE: sprawdzanie_ruchów
  maciek-gałąź/sprawdzanie_ruchów
Labels: ważne
